# Generated by Django 3.0.8 on 2021-06-07 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_message',
            name='Important',
        ),
    ]
